[package]
name = "phonemes"
version = "1.0.0"
authors = ["Kevin Glocker <kevin.glocker@liu.se>"]
edition = "2021"

[dependencies]
pyo3 = "0.17"
paste = "1.0"
aho-corasick = "0.7"

[lib]
crate-type = ["cdylib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
